name: GS1 Encoders CI

on:
  push:
  pull_request:

jobs:

  #
  #  CI jobs
  #

  ci-clang:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: clang CI
      run: |
        make -C src/c-lib -j `nproc` test CC=clang SANITIZE=yes
        make -C src/c-lib -j `nproc` lib CC=clang SANITIZE=yes
        make -C src/c-lib -j `nproc` app CC=clang SANITIZE=yes
        LD_LIBRARY_PATH=src/c-lib/build src/c-lib/build/gs1encoders.bin --version
        make -C src/c-lib -j `nproc` app-static CC=clang SANITIZE=yes
        src/c-lib/build/gs1encoders-linux.bin --version

  ci-gcc:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: gcc CI
      run: |
        make -C src/c-lib -j `nproc` test CC=gcc
        make -C src/c-lib -j `nproc` lib CC=gcc
        make -C src/c-lib -j `nproc` app CC=gcc
        LD_LIBRARY_PATH=src/c-lib/build src/c-lib/build/gs1encoders.bin --version
        make -C src/c-lib -j `nproc` app-static CC=gcc
        src/c-lib/build/gs1encoders-linux.bin --version

  ci-msvc:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: MSVC CI
      working-directory: src
      run: |
        msbuild /p:Configuration=release /p:Platform="x64" gs1encoders.sln
        c-lib\build\test\x64\Release\gs1encoders-test.exe
        c-lib\build\console-app\x64\Release\gs1encoders-app.exe --version
        dotnet\bin\Release\gs1encoders-dotnet.exe --version

  ci-scan-build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: clang static analyser CI
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install clang-tools
        scan-build -o plist make -C src/c-lib -j `nproc` test CC=clang
        scan-build -o plist make -C src/c-lib -j `nproc` lib CC=clang
        scan-build -o plist make -C src/c-lib -j `nproc` app CC=clang
        scan-build -o plist make -C src/c-lib -j `nproc` app-static CC=clang
        [ "$(find plist/ -name *.html)" = '' ];

    - name: "clang static analyzer: Store assets on failure"
      uses: actions/upload-artifact@v2
      with:
        name: clang-scan.tgz
        path: plist/**/*.html
        retention-days: 30
      if: ${{ failure() }}


  #
  #  Production builds
  #

  build-release-windows:

    if: startsWith(github.ref, 'refs/tags/')

    needs:
      - ci-gcc
      - ci-clang
      - ci-msvc

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Windows release build
      working-directory: src
      run: |
        msbuild /p:Configuration=release /p:Platform="x64" gs1encoders.sln

    - name: Exercise applications
      run: |
        src\c-lib\build\console-app\x64\Release\gs1encoders-app.exe --version
        src\dotnet\bin\Release\gs1encoders-dotnet.exe --version

    - name: ZIP development libs
      working-directory: src/c-lib/build/console-app/x64/Release
      run: |
        7z a gs1encoders-windows-libs.zip gs1encoders.h gs1encoders.lib gs1encoders.dll

    - name: ZIP application
      working-directory: src/c-lib/build/console-app/x64/Release
      run: |
        7z a gs1encoders-windows-app.zip gs1encoders-app.exe gs1encoders.dll

    - name: Store Windows development libs
      uses: actions/upload-artifact@v2
      with:
        name: windows-libs
        path: src/c-lib/build/console-app/x64/Release/gs1encoders-windows-libs.zip

    - name: Store Windows app
      uses: actions/upload-artifact@v2
      with:
        name: windows-app
        path: src/c-lib/build/console-app/x64/Release/gs1encoders-windows-app.zip


  build-release-linux:

    if: startsWith(github.ref, 'refs/tags/')

    needs:
      - ci-gcc
      - ci-clang
      - ci-msvc

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Linux release build
      run: |
        make -C src/c-lib -j `nproc` CC=clang
        src/c-lib/build/gs1encoders-linux.bin --version

    - name: Store Linux build
      uses: actions/upload-artifact@v2
      with:
        name: linux-app
        path: src/c-lib/build/gs1encoders-linux.bin


  #
  #  Create release and upload artifacts
  #

  create-release:

    runs-on: ubuntu-latest

    needs:
      - build-release-linux
      - build-release-windows

    steps:

    - name: Load Windows libs
      uses: actions/download-artifact@v2
      with:
        name: windows-libs

    - name: Load Windows app
      uses: actions/download-artifact@v2
      with:
        name: windows-app

    - name: Load Linux app
      uses: actions/download-artifact@v2
      with:
        name: linux-app

    - name: Get version
      id: get_version
      run: |
        VERSION=${GITHUB_REF/refs\/tags\//}
        echo ::set-output name=VERSION::$VERSION

    - name: Create GitHub release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: "Upload asset: Windows development libs"
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: gs1encoders-windows-libs.zip
        asset_name: gs1encoders-windows-libs.zip
        asset_content_type: application/zip

    - name: "Upload asset: Windows application"
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: gs1encoders-windows-app.zip
        asset_name: gs1encoders-windows-app.zip
        asset_content_type: application/zip

    - name: "Upload asset: Linux bin"
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: gs1encoders-linux.bin
        asset_name: gs1encoders-linux.bin
        asset_content_type: application/octet-stream

